### PR TITLE
Fix wrong dynamic malloc

### PR DESCRIPTION
**Pull request by AnderBiguri**
related #555, fixes evguenis bug report.

### CODE REVIEW

**Review by KrisThielemans — CHANGES_REQUESTED** [review]
Allocating and pointers have the risk of leaking if any exceptions are thrown. They also slow things down. What about doing
```c++
const int max_dataset_Ndims=100;
...

if (dataset_list_Ndims > max_dataset_Ndims)
  error(...);
hsize_t dims_out[max_dataset_Ndims];
```
Stack allocation is very cheap. max size is probably 5, but we can play it very safe.

**Comment by AnderBiguri** [comment]
Agree, stack is better. We may even be able to just do `const int max_dataset_Ndims=5` or something like that, I doubt any data will have high dimensionality. 

I am however surprised the previous version worked and didn't error at compilation...

**Comment by AnderBiguri** [comment]
Should I add a `#define MAX_DATASET_NDIMS` to keep it cleaner, maybe?

**Comment by KrisThielemans** [comment]
> I am however surprised the previous version worked and didn't error at compilation...

C++-14 allows it I believe. gcc has an extension. Apparently Visual Studio and clang as well, otherwise we would have had CI errors.

> Should I add a `#define MAX_DATASET_NDIMS` to keep it cleaner, maybe?

I vastly prefer `const int`. You can put it at the top of the file if you want (might have to think then about visibility outside, which isn't something that we want), or as private `const` member.

**Pull request merged**
